export interface Driver {
  id?: number;
  serialNo?: number; // Auto-generated by backend
  date: string;
  vehicleNo: string;
  driverName?: string;
  startedFrom: string;
  destination: string;
  carryMaterialType: string;
  contactNumber?: string;
  address: string;
}
